import { Inter } from "next/font/google";
import "../globals.css";
import { NextIntlClientProvider } from "next-intl";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children, params }) {
  const { locale } = await params;
  const messages = await import(`@/src/i18n/messages/${locale}.json`).then(
    (m) => m.default
  );
  const dir = locale === "ar" ? "rtl" : "ltr";
  // console.log(locale, messages);
  return (
    <html
      lang="en"
      dir={dir}
      className={`${inter.variable}  h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <NextIntlClientProvider locale={locale} messages={messages}>
          {children}
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
